Create migrations & MVC for users, reviews and murals & registration form
MrBlooKangaroo/muralis pull request #3
Opened 2018-10-16 18:22 UTC by mrjoshdev

Add controllers for murals, users and reviews & models for murals, users and reviews & views for murals index page and new registration form & created migrations for murals, users and reviews

2018-10-16 19:22 UTC, dpickett requested changes
ok - so ideally you should be separating your branches by features. There's a lot here around disparate features, so try to use topic branches that are more reflective of incremental business value. 

I've also shared a few updates that are required prior to merging this in.

Great job here, otherwise! good stuff.

2018-10-16 19:22 UTC, dpickett commented on app/controllers/users_controller.rb
> +  def create
this controller action looks like there is a syntax error. Missing `end`

2018-10-16 19:22 UTC, dpickett commented on app/models/mural.rb
> +  validates_presence_of :title, :description, :location, :photo, :upvotes, :downvotes
I recommend separate lines for each validation for readability purposes

```
validates :title, presence: true
validates :description, presence: true
```

2018-10-16 19:22 UTC, dpickett commented on spec/features/visitor_sees_list_of_murals_spec.rb
> +    testuser = User.create(first_name: 'Name', last_name: 'last', email: 'happyboi@gmail', password: '12345678')
consider the use of `create!` so that your tests yell at you if saving these records fails.

2018-10-17 18:56 UTC, bkincart requested changes
Good work on what you have here! We definitely need some more tests though. Specifically:
- Model tests for user additional attributes
- Model tests for reviews and murals

2018-10-17 18:56 UTC, bkincart commented on app/models/review.rb
> +  validates :rating, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 10 }
FYI you don't need to validate presence here since numericality is doing it by default!

2018-10-17 18:56 UTC, bkincart commented on app/controllers/users_controller.rb
> +end
Please fix your indentation here!

2018-10-18 17:35 UTC, bkincart approved these changes

2018-10-18 17:36 UTC, merged